export const CHANGE_SONG_DETAIL = "CHANGE_SONG_DETAIL";
export const CHANGE_PLAYER_LIST = "CHANGE_PLAYER_LIST";
export const CHANE_CURRENT_SONG_INDEX = "CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_SEQUENCE = "CHANGE_SEQUENCE";
export const CHANGE_LYRIC_LIST = "CHANGE_LYRIC_LIST";
export const CHANGE_CURRENT_LYRIC_INDEX = "CHANGE_CURRENT_LYRIC_INDEX"