export const CHANGE_BANNER = 'CHANGE_BANNER';
export const CHANGE_HOT_RECOMEND = "CHANGE_HOT_RECOMEND";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";
export const CHANGE_UP_RANK = "CHANGE_UP_RANK";
export const CHANGE_NEW_RANK = "CHANGE_NEW_RANK";
export const CHANGE_ORIGIN_RANK = "CHANGE_ORIGIN_RANK";
export const CHANGE_HOME_SINGERS = "CHANGE_HOME_SINGERS";